# Generated by Django 2.0.5 on 2018-05-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20180525_0359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='persontag',
            unique_together={('person', 'tag')},
        ),
    ]
