# Generated by Django 2.0.5 on 2018-05-30 03:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20180525_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='persontag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
